INSERT INTO Kanjilist (character, meaning, onyomi, kunyomi, answer1, answer2, answer3, answer4)
VALUES 
('木', 'tree', 'moku', 'ki', 'tree', 'leaf', 'tower', 'star'),
('川', 'river', 'sen', 'kawa', 'lines', 'river', 'road', 'scratch'),
('雨', 'rain', 'u', 'ame', 'snow', 'storm', 'dew', 'rain'),
('山', 'mountain', 'san', 'yama', 'gate', 'building', 'mountain', 'cliff'),
('月', 'moon', 'getsu','tsuki','moon','powder','tea','compost'),
('右', 'right', 'u','migi','glass','miss','right','timer'),
('左', 'left', 'sa','hidari','fall','jewelry','left','meal'),
('白', 'white', 'haku','shiro','thumb','white','column','potato'),
('安', 'cheap','an','yasu-i','bongo','joke','radish','cheap'),
('心', 'heart','shin','kokoro','storm','heart','quarter','hut'),
('友', 'friend','yuu','tomo','friend','dark','front','trail'),
('生', 'life','sei','i-kiru','tights','horse','swim','life'),
('日', 'sun', 'nichi','hi','carriage','recess','territory','sun'),
('火', 'fire', 'ka','hi','fire','drawing','grade','client'),
('会', 'meeting','kai','a-u','meeting','punch','raft','emu'),
('天', 'heaven','ten','amatsu','cup','heaven','page','point'),
('少', 'few','shou','suku-nai','locket','melody','few','mother'),
('女', 'woman', 'jo','onna','wheel','fort','believe','woman'),
('男', 'man','dan','otoko','man','slipper','sprout','aid'),
('水', 'water','sui','mizu','hurry','water','tough','table'),
('東', 'east','tou','higashi','waterfall','jar','east','trailer'),
('西', 'west','sei','nishi','sing','humor','air','west'),
('北', 'north','hoku','kita','north','washcloth','happy','complaint'),
('南', 'south','nan','minami','shed','south','story','employee'),
('気', 'spirit','ki','iki','whistle','cereal','spirit','book'),
('一', 'one','ichi','hito-tsu','line','just','stick','one'),
('二', 'two', 'ni','futa-tsu','two','dance','bar','handle'),
('三', 'three', 'san','mi-tsu','hawk','three','glove','trouble'),
('四', 'four', 'shi','yo-tsu','poem','hose','four','give'),
('五', 'five', 'go', 'itsu-tsu','five','video','flavor','money'),
('六', 'six', 'roku','mu-tsu','headlight','sail','grass','six'),
('七', 'seven', 'shichi','nana-tsu','seven','spinach','walk','luggage'),
('八', 'eight', 'hachi','ya-tsu','lamp','color','eight','tooth'),
('九', 'nine', 'kyuu','kokono-tsu','sun','film','sand','nine'),
('十', 'ten', 'jyuu','tou','ten','hill','pay','deer'),
('店', 'store','ten','mise','assign','store','cricket','throat'),
('電', 'electricity', 'den', 'den','squirrel','throat','electricity','delay'),
('手', 'hand','shu','te','hand','you','officer','blue'),
('人', 'person','jin','hito','green','sheet','rocket','person'),
('毎', 'every','mai','goto','damage','every','understand','top'),
('金', 'money', 'kin', 'kane','effort','combat','money','weather'),
('新', 'new', 'shin', 'atara-shi','strawberry','new','ask','battle'),
('子', 'child','shi','ko','skill','song','cloth','child'),
('先', 'previous','sen','saki','previous','open','milk','freedom'),
('車', 'car','sha','kuruma','spice','car','shirt','noise'),
('肉', 'meat','niku','shishi','nose','thunder','meat','jellyfish'),
('茶', 'tea','sa','cha','farmer','uncle','catch','tea'),
('土', 'soil','do','tsuchi','soldier','bonus','soil','math'),
('春', 'spring', 'shun', 'haru','spring','ride','boat','eyebrow'),
('夏', 'summer','ka','natsu','stone','summer','normal','build'),
('冬', 'winter','tou','fuyu','law','brush','winter','suitcase'),
('秋', 'autumn','shuu', 'aki','friend','saddle','join','autumn'),
('上', 'above','jou','ue','candy','above','cost','nursery'),
('下', 'below','ka','shita','blue','three','below','assist'),
('愛', 'love','ai','me-deru','equal','purse','stand','love'),
('犬', 'dog','ken','inu','dog','teller','recover','milk'),
('魚', 'fish','gyo','sakana','floor','fish','seed','culture'),
('鳥', 'bird','chou','tori','brain','guilt','bird','jump'),
('雪', 'snow','setsu','yuki','trout','mix','image','snow'),
('朝', 'morning','chou','asa','morning','tailor','pile','fight'),
('夢', 'dream','mu', 'yume','door','dream','fiction','yellow'),
('猫', 'cat','byou','neko','chill','dig','cat','welcome'),
('星', 'star','sei', 'hoshi','doctor','web','dog','star'),
('強', 'strong','kyou','tsuyo-i','strong','buddy','snore','village'),
('弱', 'weak','jaku','yowa-i','ear','weak','hood','berry'),
('宝', 'treasure','hou','takara','comfort','bed','treasure','spy'),
('花', 'flower','ka','hana','nail','red','tempo','flower'),
('年', 'year','nen','toshi','year','bass','capital','spiral'),
('名', 'name','mei','na','octopus','name','fist','group'),
('本', 'book','hon','moto','hide','fox','book','love'),
('文', 'sentence','bun','fumi','cherry','cut','heart','sentence'),
('大', 'big','dai','oo-kii','big','blank','flag','cloud'),
('早', 'fast','sou','haya-i','alien','fast','shark','dusk'),
('草', 'grass','sou','kusa','bone','wife','grass','sponge'),
('林', 'woods','rin','hayashi','quick','cage','bee','woods'),
('森', 'forest','shin','mori','forest','fix','nature','run'),
('耳', 'ear','ji','mimi','adult','ear','sky','eyes'),
('糸', 'thread','shi','ito','beard','coconut','thread','bell'),
('公', 'public','kou','ooyake','ring','fade','grape','public'),
('高', 'high', 'kou','taka-i','high','purple','sound','dirt'),
('虫', 'bug','chuu','mushi','hippo','bug','snake','dolphin'),
('中', 'middle','chuu','naka','almond','planet','middle','hand'),
('字', 'character','ji','azana','bag','famous','robot','character'),
('学', 'learning','gaku','mana-bu','learning','donut','apple','daylight');